- name: Update apt cache
  apt:
    update_cache: yes

- name: Install packages
  package:
    name:
      - ufw

- name: Allow rate limited connections to SSH
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: Deny everything else and enable UFW
  community.general.ufw:
    state: enabled
    policy: deny