- name: Add an Ansible apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 93C4A3FD7BB9C367

- name: Adds gcloud key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adds gcloud repos
  apt_repository:
    repo: "deb http://packages.cloud.google.com/apt cloud-sdk main"
    update_cache: no

- name: "Add Ansible Repository"
  apt_repository:
    repo: deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main
    state: present
    update_cache: true

- name: Install packages
  package:
    name:
      - apt-transport-https
      - autoconf 
      - build-essential
      - ca-certificates
      - direnv
      - fop 
      - git
      - gnupg
      - google-cloud-sdk
      - htop
      - libgl1-mesa-dev
      - libglu1-mesa-dev 
      - libmagickwand-dev
      - libncurses-dev 
      - libncurses5-dev
      - libpng-dev 
      - libpq-dev
      - libreadline-dev
      - libssh-dev 
      - libwxgtk3.0-gtk3-dev
      - libxml2-utils 
      - m4
      - openjdk-11-jdk 
      - rsync
      - sudo
      - tmux
      - unixodbc-dev 
      - unzip
      - vim
      - xsltproc 
      - zsh

- name: Add the main user
  user:
    name: "{{ main_user }}"
    group: sudo

- name: Allow the main user to login via SSH
  ansible.posix.authorized_key:
    user: "{{ main_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: set the main users shell
  user:
    name: "{{ main_user }}"
    shell: /usr/bin/zsh

- name: Install Oh My ZSH
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become: yes
  become_user: "{{ main_user }}"
  args:
    creates: "/home/{{ main_user }}/.oh-my-zsh"

- name: Install AWS ClI
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    sudo rm -rf ./aws
    sudo rm awscliv2.zip
  args:
    creates: /usr/local/bin/aws

- name: Increase inotify user limit
  sysctl: name=fs.inotify.max_user_watches value=524288 sysctl_set=yes