- name: Install packages
  package:
    name:
      - curl
      - git

- name: Git checkout
  git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: ~/.asdf
    version: v0.8.0
  become_user: "{{ main_user }}"
  become: yes

- name: "Install asdf plugins"
  shell: |
    source /home/{{ main_user }}/.asdf/asdf.sh
    asdf plugin-add {{ item }} || exit 0
  with_items:
    - ruby
    - elixir
    - nodejs
    - yarn
    - python
    - erlang https://github.com/asdf-vm/asdf-erlang.git
  become_user: "{{ main_user }}"
  become: yes
  args:
     executable: /bin/bash

- name: "Install yarn"
  shell: |
    source /home/{{ main_user }}/.asdf/asdf.sh
    asdf install yarn latest
    asdf install yarn 1.22.10
    asdf global yarn latest
    asdf reshim python
  become_user: "{{ main_user }}"
  become: yes
  args:
     executable: /bin/bash

- name: "Install Default Python"
  shell: |
    source /home/{{ main_user }}/.asdf/asdf.sh
    asdf install python 3.7.3
    asdf global python 3.7.3
    pip3 install boto
    pip3 install ansible
    pip3 install jupyterlab
    pip3 isntall numpy 
    pip3 install scipy
    pip3 install matplotlib 
    pip3 install ipython 
    pip3 install jupyter
    pip3 install pandas
    pip3 install sympy
    pip3 install nose
    pip3 install scikit-learn
    asdf reshim python
  become_user: "{{ main_user }}"
  become: yes
  args:
     executable: /bin/bash

- name: "Install Default Ruby"
  shell: |
    source /home/{{ main_user }}/.asdf/asdf.sh
    asdf install ruby 2.7.2
    asdf install ruby 2.6.4
    asdf global ruby 2.7.2
    gem install bundler -v 1.17.3
    gem install solargraph
    gem install rubocop
  become_user: "{{ main_user }}"
  become: yes
  args:
     executable: /bin/bash

- name: "Install default node"
  shell: |
    source /home/{{ main_user }}/.asdf/asdf.sh
    bash /home/{{ main_user }}/.asdf/plugins/nodejs/bin/import-release-team-keyring
    asdf install nodejs 14.15.1
    asdf install nodejs 12.18.4
    asdf global nodejs 14.15.1
  become_user: "{{ main_user }}"
  become: yes
  args:
     executable: /bin/bash

- name: "Install default erlang"
  shell: |
    source /home/{{ main_user }}/.asdf/asdf.sh
    asdf install erlang 23.2.1
    asdf global erlang 23.2.1
  become_user: "{{ main_user }}"
  become: yes
  args:
     executable: /bin/bash

- name: "Install default elixir"
  shell: |
    source /home/{{ main_user }}/.asdf/asdf.sh
    asdf install elixir 1.11.2
    asdf global elixir 1.11.2
    mix local.hex --force
    mix archive.install hex phx_new 1.5.7 --force
  become_user: "{{ main_user }}"
  become: yes
  args:
     executable: /bin/bash